# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jan/projects/librexgen

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jan/projects/librexgen

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jan/projects/librexgen/CMakeFiles /home/jan/projects/librexgen/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jan/projects/librexgen/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named librexgen

# Build rule for target.
librexgen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 librexgen
.PHONY : librexgen

# fast build rule for target.
librexgen/fast:
	$(MAKE) -f CMakeFiles/librexgen.dir/build.make CMakeFiles/librexgen.dir/build
.PHONY : librexgen/fast

Regex.o: Regex.cpp.o
.PHONY : Regex.o

# target to build an object file
Regex.cpp.o:
	$(MAKE) -f CMakeFiles/librexgen.dir/build.make CMakeFiles/librexgen.dir/Regex.cpp.o
.PHONY : Regex.cpp.o

Regex.i: Regex.cpp.i
.PHONY : Regex.i

# target to preprocess a source file
Regex.cpp.i:
	$(MAKE) -f CMakeFiles/librexgen.dir/build.make CMakeFiles/librexgen.dir/Regex.cpp.i
.PHONY : Regex.cpp.i

Regex.s: Regex.cpp.s
.PHONY : Regex.s

# target to generate assembly for a file
Regex.cpp.s:
	$(MAKE) -f CMakeFiles/librexgen.dir/build.make CMakeFiles/librexgen.dir/Regex.cpp.s
.PHONY : Regex.cpp.s

TerminalRegex.o: TerminalRegex.cpp.o
.PHONY : TerminalRegex.o

# target to build an object file
TerminalRegex.cpp.o:
	$(MAKE) -f CMakeFiles/librexgen.dir/build.make CMakeFiles/librexgen.dir/TerminalRegex.cpp.o
.PHONY : TerminalRegex.cpp.o

TerminalRegex.i: TerminalRegex.cpp.i
.PHONY : TerminalRegex.i

# target to preprocess a source file
TerminalRegex.cpp.i:
	$(MAKE) -f CMakeFiles/librexgen.dir/build.make CMakeFiles/librexgen.dir/TerminalRegex.cpp.i
.PHONY : TerminalRegex.cpp.i

TerminalRegex.s: TerminalRegex.cpp.s
.PHONY : TerminalRegex.s

# target to generate assembly for a file
TerminalRegex.cpp.s:
	$(MAKE) -f CMakeFiles/librexgen.dir/build.make CMakeFiles/librexgen.dir/TerminalRegex.cpp.s
.PHONY : TerminalRegex.cpp.s

classregex.o: classregex.cpp.o
.PHONY : classregex.o

# target to build an object file
classregex.cpp.o:
	$(MAKE) -f CMakeFiles/librexgen.dir/build.make CMakeFiles/librexgen.dir/classregex.cpp.o
.PHONY : classregex.cpp.o

classregex.i: classregex.cpp.i
.PHONY : classregex.i

# target to preprocess a source file
classregex.cpp.i:
	$(MAKE) -f CMakeFiles/librexgen.dir/build.make CMakeFiles/librexgen.dir/classregex.cpp.i
.PHONY : classregex.cpp.i

classregex.s: classregex.cpp.s
.PHONY : classregex.s

# target to generate assembly for a file
classregex.cpp.s:
	$(MAKE) -f CMakeFiles/librexgen.dir/build.make CMakeFiles/librexgen.dir/classregex.cpp.s
.PHONY : classregex.cpp.s

compoundregex.o: compoundregex.cpp.o
.PHONY : compoundregex.o

# target to build an object file
compoundregex.cpp.o:
	$(MAKE) -f CMakeFiles/librexgen.dir/build.make CMakeFiles/librexgen.dir/compoundregex.cpp.o
.PHONY : compoundregex.cpp.o

compoundregex.i: compoundregex.cpp.i
.PHONY : compoundregex.i

# target to preprocess a source file
compoundregex.cpp.i:
	$(MAKE) -f CMakeFiles/librexgen.dir/build.make CMakeFiles/librexgen.dir/compoundregex.cpp.i
.PHONY : compoundregex.cpp.i

compoundregex.s: compoundregex.cpp.s
.PHONY : compoundregex.s

# target to generate assembly for a file
compoundregex.cpp.s:
	$(MAKE) -f CMakeFiles/librexgen.dir/build.make CMakeFiles/librexgen.dir/compoundregex.cpp.s
.PHONY : compoundregex.cpp.s

lexer.o: lexer.cpp.o
.PHONY : lexer.o

# target to build an object file
lexer.cpp.o:
	$(MAKE) -f CMakeFiles/librexgen.dir/build.make CMakeFiles/librexgen.dir/lexer.cpp.o
.PHONY : lexer.cpp.o

lexer.i: lexer.cpp.i
.PHONY : lexer.i

# target to preprocess a source file
lexer.cpp.i:
	$(MAKE) -f CMakeFiles/librexgen.dir/build.make CMakeFiles/librexgen.dir/lexer.cpp.i
.PHONY : lexer.cpp.i

lexer.s: lexer.cpp.s
.PHONY : lexer.s

# target to generate assembly for a file
lexer.cpp.s:
	$(MAKE) -f CMakeFiles/librexgen.dir/build.make CMakeFiles/librexgen.dir/lexer.cpp.s
.PHONY : lexer.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/librexgen.dir/build.make CMakeFiles/librexgen.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/librexgen.dir/build.make CMakeFiles/librexgen.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/librexgen.dir/build.make CMakeFiles/librexgen.dir/main.cpp.s
.PHONY : main.cpp.s

parser.o: parser.cpp.o
.PHONY : parser.o

# target to build an object file
parser.cpp.o:
	$(MAKE) -f CMakeFiles/librexgen.dir/build.make CMakeFiles/librexgen.dir/parser.cpp.o
.PHONY : parser.cpp.o

parser.i: parser.cpp.i
.PHONY : parser.i

# target to preprocess a source file
parser.cpp.i:
	$(MAKE) -f CMakeFiles/librexgen.dir/build.make CMakeFiles/librexgen.dir/parser.cpp.i
.PHONY : parser.cpp.i

parser.s: parser.cpp.s
.PHONY : parser.s

# target to generate assembly for a file
parser.cpp.s:
	$(MAKE) -f CMakeFiles/librexgen.dir/build.make CMakeFiles/librexgen.dir/parser.cpp.s
.PHONY : parser.cpp.s

regexalternatives.o: regexalternatives.cpp.o
.PHONY : regexalternatives.o

# target to build an object file
regexalternatives.cpp.o:
	$(MAKE) -f CMakeFiles/librexgen.dir/build.make CMakeFiles/librexgen.dir/regexalternatives.cpp.o
.PHONY : regexalternatives.cpp.o

regexalternatives.i: regexalternatives.cpp.i
.PHONY : regexalternatives.i

# target to preprocess a source file
regexalternatives.cpp.i:
	$(MAKE) -f CMakeFiles/librexgen.dir/build.make CMakeFiles/librexgen.dir/regexalternatives.cpp.i
.PHONY : regexalternatives.cpp.i

regexalternatives.s: regexalternatives.cpp.s
.PHONY : regexalternatives.s

# target to generate assembly for a file
regexalternatives.cpp.s:
	$(MAKE) -f CMakeFiles/librexgen.dir/build.make CMakeFiles/librexgen.dir/regexalternatives.cpp.s
.PHONY : regexalternatives.cpp.s

unicode.o: unicode.cpp.o
.PHONY : unicode.o

# target to build an object file
unicode.cpp.o:
	$(MAKE) -f CMakeFiles/librexgen.dir/build.make CMakeFiles/librexgen.dir/unicode.cpp.o
.PHONY : unicode.cpp.o

unicode.i: unicode.cpp.i
.PHONY : unicode.i

# target to preprocess a source file
unicode.cpp.i:
	$(MAKE) -f CMakeFiles/librexgen.dir/build.make CMakeFiles/librexgen.dir/unicode.cpp.i
.PHONY : unicode.cpp.i

unicode.s: unicode.cpp.s
.PHONY : unicode.s

# target to generate assembly for a file
unicode.cpp.s:
	$(MAKE) -f CMakeFiles/librexgen.dir/build.make CMakeFiles/librexgen.dir/unicode.cpp.s
.PHONY : unicode.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... librexgen"
	@echo "... rebuild_cache"
	@echo "... Regex.o"
	@echo "... Regex.i"
	@echo "... Regex.s"
	@echo "... TerminalRegex.o"
	@echo "... TerminalRegex.i"
	@echo "... TerminalRegex.s"
	@echo "... classregex.o"
	@echo "... classregex.i"
	@echo "... classregex.s"
	@echo "... compoundregex.o"
	@echo "... compoundregex.i"
	@echo "... compoundregex.s"
	@echo "... lexer.o"
	@echo "... lexer.i"
	@echo "... lexer.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... parser.o"
	@echo "... parser.i"
	@echo "... parser.s"
	@echo "... regexalternatives.o"
	@echo "... regexalternatives.i"
	@echo "... regexalternatives.s"
	@echo "... unicode.o"
	@echo "... unicode.i"
	@echo "... unicode.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

