function(target_enable_coverage target excluded_files)
    target_compile_options(${target} PUBLIC       "-fprofile-instr-generate"    "-fcoverage-mapping")
    set_source_files_properties(${excluded_files} "-fno-profile-instr-generate" "-fno-coverage-mapping")
    target_link_libraries(${target}               "-fprofile-instr-generate"    "-fcoverage-mapping")
endfunction()

function(target_enable_fuzzing target excluded_files)
    target_compile_options(${target} PUBLIC       "-fsanitize=fuzzer"    "-fsanitize=address")
    # do not disable address sanitizer for any code, because:
    # https://github.com/google/sanitizers/wiki/AddressSanitizerContainerOverflow
    set_source_files_properties(${excluded_files} "-fno-sanitize=fuzzer")
    target_link_libraries(${target}               "-fsanitize=fuzzer"    "-fsanitize=address")
endfunction()

function(enable_fuzzing)
    add_compile_definitions("USE_LIBFUZZER")
    add_compile_options("-fsanitize=fuzzer-no-link")
    add_compile_options("-fsanitize=address")
    add_link_options   ("-fsanitize=fuzzer-no-link")
    add_link_options   ("-fsanitize=address")
endfunction()

function(enable_coverage)
    if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
        message(STATUS "adding test coverage instrumentation for gcc")
        add_compile_options("-fprofile-arcs")
        add_compile_options("-ftest-coverage")
        add_link_options("-lgcov")
    elseif("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
        message(STATUS "adding test coverage instrumentation for clang")
        add_compile_options("-fprofile-instr-generate")
        add_compile_options("-fcoverage-mapping")
        add_link_options("-fprofile-instr-generate")
        add_link_options("-fcoverage-mapping")
    else()
        message(STATUS "adding test coverage instrumentation for ${CMAKE_CXX_COMPILER_ID}")
        add_compile_options("-fprofile-instr-generate")
        add_compile_options("-fcoverage-mapping")
        add_link_options("-fprofile-instr-generate")
        add_link_options("-fcoverage-mapping")
    endif ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
endfunction()

function(enable_debug)
    add_compile_definitions("DEBUG")
    add_compile_options("-g")
    add_compile_options("-O0")
    add_link_options("-g")
endfunction()